/**
 * Database types for the TSSS application.
 *
 * Hand maintained to match supabase/migrations/0001_init.sql.
 * Regenerate with the Supabase CLI (`supabase gen types typescript`) when the
 * schema changes and keep this file in sync.
 */

export type AppRole = "super_admin" | "admin" | "content_manager" | "blood_help_manager";
export type MemberStatus = "active" | "disabled";
export type BlogStatus = "pending" | "approved" | "rejected" | "unpublished";
export type MediaType = "youtube" | "news";
export type BannerType = "info" | "success" | "warning" | "urgent";
export type BloodRequestStatus = "NEW" | "CONTACTED" | "IN_PROGRESS" | "RESOLVED" | "CLOSED";
export type NotificationType = "email" | "whatsapp";
export type NotificationStatus = "pending" | "sent" | "failed" | "skipped";

export interface UserRow {
  id: string;
  email: string;
  full_name: string | null;
  role: AppRole;
  is_active: boolean;
  created_at: string;
  updated_at: string;
}

export interface SiteBannerRow {
  id: string;
  message: string;
  banner_type: BannerType;
  link_url: string | null;
  link_label: string | null;
  is_enabled: boolean;
  /** Generated by the database: enabled AND inside the optional date window. */
  is_visible?: boolean;
  start_date: string | null;
  end_date: string | null;
  created_by: string | null;
  created_at: string;
  updated_at: string;
}

export interface EventCategoryRow {
  id: string;
  name: string;
  slug: string;
  description: string | null;
  cover_image: string | null;
  display_order: number;
  is_active: boolean;
  created_at: string;
  updated_at: string;
}

export interface EventRow {
  id: string;
  category_id: string;
  title: string;
  slug: string;
  event_date: string;
  end_date: string | null;
  location: string | null;
  summary: string | null;
  content: string | null;
  cover_image: string | null;
  youtube_url: string | null;
  external_links: string | null;
  is_featured: boolean;
  is_published: boolean;
  created_by: string | null;
  created_at: string;
  updated_at: string;
}

export type EventWithCategory = EventRow & {
  event_categories: Pick<EventCategoryRow, "id" | "name" | "slug"> | null;
};

export interface EventGalleryRow {
  id: string;
  event_id: string;
  image_url: string;
  caption: string | null;
  display_order: number;
  created_at: string;
}

export interface DonationSettingsRow {
  id: string;
  account_name: string | null;
  bank_name: string | null;
  account_number: string | null;
  ifsc: string | null;
  branch: string | null;
  upi_id: string | null;
  qr_code_url: string | null;
  instructions: string | null;
  transparency_note: string | null;
  is_donation_open: boolean;
  updated_by: string | null;
  updated_at: string;
}

export interface MediaItemRow {
  id: string;
  type: MediaType;
  title: string;
  description: string | null;
  url: string;
  thumbnail_url: string | null;
  source_name: string | null;
  publication_date: string | null;
  display_order: number;
  is_published: boolean;
  created_by: string | null;
  created_at: string;
  updated_at: string;
}

export interface BlogRow {
  id: string;
  author_name: string;
  author_email: string;
  author_mobile: string | null;
  title: string;
  slug: string;
  excerpt: string | null;
  content: string;
  featured_image: string | null;
  category: string;
  status: BlogStatus;
  is_featured: boolean;
  reviewed_by: string | null;
  reviewed_at: string | null;
  review_note: string | null;
  created_at: string;
  updated_at: string;
}

export interface MemberRow {
  id: string;
  registration_number: string;
  full_name: string;
  normalized_full_name: string;
  date_of_birth: string;
  village: string | null;
  mobile_number: string;
  normalized_mobile: string;
  email: string | null;
  status: MemberStatus;
  notes: string | null;
  created_at: string;
  updated_at: string;
}

export interface DistrictRow {
  id: string;
  name: string;
  slug: string;
  is_active: boolean;
  display_order: number;
  created_at: string;
  updated_at: string;
}

export interface AreaRow {
  id: string;
  district_id: string;
  name: string;
  slug: string;
  is_active: boolean;
  display_order: number;
  created_at: string;
  updated_at: string;
}

export interface BloodHelpAdminRow {
  id: string;
  district_id: string | null;
  area_id: string | null;
  admin_name: string;
  email: string | null;
  whatsapp_number: string | null;
  phone_number: string | null;
  is_active: boolean;
  created_at: string;
  updated_at: string;
}

export interface BloodHelpRequestRow {
  id: string;
  request_number: string;
  requester_name: string;
  mobile_number: string;
  blood_group: string;
  hospital_name: string;
  hospital_location: string | null;
  district_id: string | null;
  area_id: string | null;
  required_date: string | null;
  units_required: number;
  message: string | null;
  status: BloodRequestStatus;
  assigned_admin_id: string | null;
  is_unassigned: boolean;
  resolution_note: string | null;
  created_at: string;
  updated_at: string;
}

export interface NotificationLogRow {
  id: string;
  blood_request_id: string | null;
  notification_type: NotificationType;
  provider: string | null;
  recipient: string | null;
  subject: string | null;
  body: string | null;
  status: NotificationStatus;
  error_message: string | null;
  provider_response: unknown | null;
  sent_at: string | null;
  created_at: string;
}

export interface PageContentRow {
  id: string;
  key: string;
  title: string | null;
  subtitle: string | null;
  body: string | null;
  meta: Record<string, unknown>;
  is_published: boolean;
  updated_by: string | null;
  updated_at: string;
}

export interface SiteSettingsRow {
  id: string;
  organization_name: string;
  short_name: string;
  tagline: string | null;
  about_short: string | null;
  mission: string | null;
  vision: string | null;
  contact_email: string | null;
  contact_phone: string | null;
  contact_address: string | null;
  whatsapp_number: string | null;
  youtube_url: string | null;
  facebook_url: string | null;
  instagram_url: string | null;
  twitter_url: string | null;
  map_embed_url: string | null;
  registration_open: boolean;
  blood_help_open: boolean;
  registration_paused_message: string | null;
  blood_help_paused_message: string | null;
  central_admin_email: string | null;
  email_notifications_enabled: boolean;
  whatsapp_notifications_enabled: boolean;
  updated_by: string | null;
  updated_at: string;
}

export type PhotoSlotShape = "rect" | "circle";

export interface PhotoBoothSlot {
  id: string;
  template_id: string;
  label: string | null;
  shape: PhotoSlotShape;
  x: number;
  y: number;
  width: number;
  height: number;
  /** Corner radius used when clipping the photo to the frame window. */
  radius: number;
  rotation: number;
  display_order: number;
  created_at: string;
}

export interface PhotoBoothTemplate {
  id: string;
  name: string;
  slug: string;
  description: string | null;
  /** Transparent PNG frame with the photo windows cut out. */
  frame_image: string;
  /** Optional JPG shown before a visitor picks the template. */
  preview_image: string | null;
  width: number;
  height: number;
  is_active: boolean;
  is_featured: boolean;
  display_order: number;
  created_by: string | null;
  created_at: string;
  updated_at: string;
}

export type PhotoBoothTemplateWithSlots = PhotoBoothTemplate & { slots: PhotoBoothSlot[] };

/** Per-slot photo placement chosen by the visitor (client side only). */
export interface PhotoPlacement {
  /** Loaded HTMLImageElement (kept in memory, never uploaded). */
  image: CanvasImageSource & { width: number; height: number };
  /** Object URL for previews; revoked when replaced. */
  url: string;
  /** Offset of the photo centre from the slot centre, in template pixels. */
  offsetX: number;
  offsetY: number;
  /** 1 = fill the slot exactly. */
  scale: number;
  /** Degrees. */
  rotation: number;
}

export interface AuditLogRow {
  id: string;
  actor_id: string | null;
  actor_email: string | null;
  action: string;
  entity: string;
  entity_id: string | null;
  previous_value: Record<string, unknown> | null;
  new_value: Record<string, unknown> | null;
  created_at: string;
}

/** Result shape returned by the submit_registration() database function. */
export interface SubmitRegistrationResult {
  result_code: "created" | "already_registered";
  registration_number: string | null;
  full_name: string | null;
  date_of_birth: string | null;
  village: string | null;
  registered_at: string | null;
}

/** Result shape returned by the create_blood_request() database function. */
export interface CreateBloodRequestResult {
  result_code: "created";
  request_id: string;
  request_number: string;
  is_unassigned: boolean;
  assigned_admin_id: string | null;
  assigned_admin_name: string | null;
  assigned_admin_email: string | null;
  assigned_admin_whatsapp: string | null;
  requester_name: string;
  mobile_number: string;
  blood_group: string;
  hospital_name: string;
  hospital_location: string | null;
  required_date: string | null;
  units_required: number;
  message: string | null;
}
