-- ===========================================================================
-- Photo Booth starter templates.
--
-- The frame PNGs live in public/images/photobooth/ (generated by
-- `npm run placeholders:photobooth`). Re-generate them if you change the slot
-- geometry, or edit the slots from Admin -> Photo Booth.
-- ===========================================================================

with templates (slug, name, description, frame_image, preview_image, width, height, display_order, is_featured) as (
  values
    ('four-photo-collage', 'Four Photo Collage',
     'One wide photo with two below - ideal for family group shots.',
     '/images/photobooth/frame-collage-4.png', '/images/photobooth/frame-collage-4-preview.jpg',
     1080, 1350, 1, true),
    ('photo-strip', 'Photo Strip',
     'Classic three photo strip, great for printing.',
     '/images/photobooth/frame-strip-3.png', '/images/photobooth/frame-strip-3-preview.jpg',
     900, 1600, 2, false),
    ('single-circle', 'Classic Circle',
     'Elegant single portrait with a circular cut-out.',
     '/images/photobooth/frame-circle.png', '/images/photobooth/frame-circle-preview.jpg',
     1080, 1080, 3, false),
    ('twin-collage', 'Twin Collage',
     'Two tall photos side by side for couples or pairs.',
     '/images/photobooth/frame-twin.png', '/images/photobooth/frame-twin-preview.jpg',
     1080, 1200, 4, false)
)
insert into public.photo_booth_templates
  (name, slug, description, frame_image, preview_image, width, height, display_order, is_featured, is_active)
select t.name, t.slug, t.description, t.frame_image, t.preview_image, t.width, t.height,
       t.display_order, t.is_featured, true
from templates t
on conflict (slug) do update
  set name = excluded.name,
      description = excluded.description,
      frame_image = excluded.frame_image,
      preview_image = excluded.preview_image,
      width = excluded.width,
      height = excluded.height,
      display_order = excluded.display_order,
      is_featured = excluded.is_featured;

with slots (template_slug, label, shape, x, y, width, height, radius, display_order) as (
  values
    ('four-photo-collage', 'Photo 1', 'rect', 90, 320, 900, 420, 28, 1),
    ('four-photo-collage', 'Photo 2', 'rect', 90, 780, 430, 380, 28, 2),
    ('four-photo-collage', 'Photo 3', 'rect', 560, 780, 430, 380, 28, 3),
    ('photo-strip', 'Photo 1', 'rect', 110, 300, 680, 330, 26, 1),
    ('photo-strip', 'Photo 2', 'rect', 110, 670, 680, 330, 26, 2),
    ('photo-strip', 'Photo 3', 'rect', 110, 1040, 680, 330, 26, 3),
    ('single-circle', 'Photo 1', 'circle', 190, 250, 700, 700, 350, 1),
    ('twin-collage', 'Photo 1', 'rect', 90, 300, 430, 640, 30, 1),
    ('twin-collage', 'Photo 2', 'rect', 560, 300, 430, 640, 30, 2)
)
insert into public.photo_booth_slots (template_id, label, shape, x, y, width, height, radius, display_order)
select t.id, s.label, s.shape::public.photo_slot_shape, s.x, s.y, s.width, s.height, s.radius, s.display_order
from slots s
join public.photo_booth_templates t on t.slug = s.template_slug
where not exists (
  select 1 from public.photo_booth_slots existing
  where existing.template_id = t.id and existing.display_order = s.display_order
);