"use client";

import { ResourceForm } from "@/components/admin/resource-form";
import { ENTITY_SPECS } from "@/lib/admin/entities";
import type { MemberRow } from "@/lib/types";
import { formatDateTime } from "@/lib/utils/format";
import { countryName, stateName } from "@/lib/lookups";

export function MemberForm({ member }: { member: MemberRow }) {
  const spec = ENTITY_SPECS.member;

  return (
    <div className="grid gap-6 lg:grid-cols-12">
      <div className="lg:col-span-4">
        <dl className="space-y-3 text-sm">
          {[
            ["Registration number", member.registration_number],
            ["Registered at", formatDateTime(member.created_at)],
            ["Last updated", formatDateTime(member.updated_at)],
            ["Normalised mobile", member.normalized_mobile],
            ["Country", countryName(member.country_code) || "—"],
            ["State", stateName(member.state_code) || "—"],
            ["Status", member.status],
          ].map(([label, value]) => (
            <div key={label} className="flex justify-between gap-4 border-b border-brand-100 pb-2">
              <dt className="text-slate-500">{label}</dt>
              <dd className="text-right font-medium text-ink-900">{value}</dd>
            </div>
          ))}
        </dl>

        <a
          href={`/api/admin/members/${member.id}/id-card`}
          className="mt-5 inline-flex h-11 w-full items-center justify-center gap-2 rounded-full bg-gradient-to-r from-brand-600 to-brand-500 px-5 text-sm font-semibold text-white transition-transform hover:scale-[1.02]"
        >
          <svg viewBox="0 0 20 20" className="size-4" fill="currentColor" aria-hidden="true">
            <path d="M10 2a3 3 0 0 1 3 3v5a3 3 0 0 1-6 0V5a3 3 0 0 1 3-3Zm-6 8h1.2a4.8 4.8 0 0 0 9.6 0H16a6 6 0 0 1-5 5.9V18H9v-2.1A6 6 0 0 1 4 10Z" />
          </svg>
          Download ID card
        </a>
        <p className="mt-2 text-xs text-slate-500">
          Regenerated from the member&apos;s current details every time, so it always reflects the
          latest edit.
        </p>

        <p className="mt-4 rounded-2xl bg-brand-50 p-3 text-xs leading-relaxed text-slate-600">
          Registration numbers are generated by a database sequence and can never be reused or edited. Editing the name
          or date of birth may conflict with another member — the database prevents duplicates.
        </p>
      </div>

      <div className="lg:col-span-8">
        <ResourceForm
          entity="member"
          fields={spec.fields}
          id={member.id}
          defaults={{
            full_name: member.full_name,
            father_name: member.father_name ?? "",
            gender: member.gender ?? "",
            blood_group: member.blood_group ?? "",
            date_of_birth: member.date_of_birth,
            village: member.village ?? "",
            state_code: member.state_code ?? "",
            country_code: member.country_code ?? "",
            phone_country_code: member.phone_country_code ?? "",
            mobile_number: member.mobile_number,
            email: member.email ?? "",
            designation: member.designation ?? "",
            profile_photo_url: member.profile_photo_url ?? "",
            status: member.status,
            notes: member.notes ?? "",
          }}
          submitLabel="Save member"
        />
      </div>
    </div>
  );
}
