"use client";

import { ResourceForm } from "@/components/admin/resource-form";
import { ENTITY_SPECS } from "@/lib/admin/entities";
import type { MemberRow } from "@/lib/types";
import { formatDateTime } from "@/lib/utils/format";

export function MemberForm({ member }: { member: MemberRow }) {
  const spec = ENTITY_SPECS.member;

  return (
    <div className="grid gap-6 lg:grid-cols-12">
      <div className="lg:col-span-4">
        <dl className="space-y-3 text-sm">
          {[
            ["Registration number", member.registration_number],
            ["Registered at", formatDateTime(member.created_at)],
            ["Last updated", formatDateTime(member.updated_at)],
            ["Normalised mobile", member.normalized_mobile],
            ["Status", member.status],
          ].map(([label, value]) => (
            <div key={label} className="flex justify-between gap-4 border-b border-brand-100 pb-2">
              <dt className="text-slate-500">{label}</dt>
              <dd className="text-right font-medium text-ink-900">{value}</dd>
            </div>
          ))}
        </dl>
        <p className="mt-4 rounded-2xl bg-brand-50 p-3 text-xs leading-relaxed text-slate-600">
          Registration numbers are generated by a database sequence and can never be reused or edited. Editing the name
          or date of birth may conflict with another member — the database prevents duplicates.
        </p>
      </div>

      <div className="lg:col-span-8">
        <ResourceForm
          entity="member"
          fields={spec.fields}
          id={member.id}
          defaults={{
            full_name: member.full_name,
            date_of_birth: member.date_of_birth,
            village: member.village ?? "",
            mobile_number: member.mobile_number,
            email: member.email ?? "",
            status: member.status,
            notes: member.notes ?? "",
          }}
          submitLabel="Save member"
        />
      </div>
    </div>
  );
}
